### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by JCBauza** [dashpay/sentinel#5]
Hi,

When installing on Ubuntu 16 LTS I get the following errors:
$ virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/<UserName>/.dashcore/sentinel/venv/bin/python2
Not overwriting existing python script /home/<UserName>/.dashcore/sentinel/venv/bin/python (you must use /home/<UserName>/.dashcore/sentinel/venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/<UserName>/.dash...nel/venv/bin/python2 - setuptools pkg_resources pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 215, in main
  File "/home/<UserName>/.dashcore/sentinel/venv/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/<UserName>/.dash...nel/venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 1

Any ideas why?

**Comment by nmarley** [comment]
It looks like you already installed virtualenv and are maybe trying to re-install it or over-write it. It also looks like you're mixing Python 2 and 3.

Note that this is not an error from Sentinel, but from virtualenv.

From the path `.dashcore/sentinel`, I'm guessing you have been following instructions posted elsewhere, because that path was never specified in the official [Sentinel README](https://github.com/dashpay/sentinel/blob/master/README.md#installation).

I suggest starting from a clean slate and following the instructions here: <https://github.com/dashpay/sentinel/blob/master/README.md#installation>
